// prisma/export.js
import { PrismaClient } from '@prisma/client';
import fs from 'fs';

const prisma = new PrismaClient();

async function main() {
  console.log('⏳ Connecting to database to extract products...');

  // 1. Fetch all products, leaving out the "id"
  const rawProducts = await prisma.product.findMany({
    select: {
      name: true,
      nameVn: true,
      brandId: true, 
      categoryId: true,
      description: true,
      ingredient: true,
      skinType: true,
      isActive: true,
      variants: {
        select: {
          sku: true,
          specification: true,
          unitPrice: true,
          thumbnailUrl: true,
          slug: true,
          images: {
            select: {
              imageUrl: true,
              displayOrder: true,
              altText: true
            }
          }
        }
      }
    }
  });

  console.log(`📦 Found ${rawProducts.length} products. Generating file...`);

  // 2. Format the data into a perfect JavaScript string
  const fileContent = `// 🛑 DO NOT EDIT THIS FILE MANUALLY.\n// 🔄 Auto-generated by export.js\n\nexport const products = ${JSON.stringify(rawProducts, null, 2)};\n`;

  // 3. Overwrite your product_data.js file with this new data
  fs.writeFileSync('data/product_data.js', fileContent);

  console.log('✅ Success! Your data is safely saved in prisma/product_data.js');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('❌ Error extracting data:', e);
    await prisma.$disconnect();
    process.exit(1);
  });